# Generated by Django 5.0.6 on 2025-12-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_address'),
        ('orders', '0010_order_discounts'),
    ]

    operations = [
    ]
